name: dev-env

services:
    dev-env:
        build:
            context: .
            dockerfile: Dockerfile
        image: dev-container:latest
        container_name: dev-env
        tty: true
        volumes:
            - .:/home:rw
